# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f92c4706812f721553911238545085d5805be038066c3c783f15347ff8bbe6a8122da277bb465a9b729d4dad0756c0631592b2e7384070141c79088410412c

test:
  secret_key_base: 29d18d91e87c6d2a134774b90440e4385ab017f2f2d215c16405dbaa1363227307a175d78efd5c4417fd43df43278f4595d5634d757574e288ff01dc83e56218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
